### ISSUE TITLE
add some instructions and screenshots please

### ISSUE THREAD

**Issue by E3V3A** [kaygisiz/Gradle-External-Library-Helper#2]
Please clarify what this plugin does. The name sound promising, but you're not saying anything what `add, sync and find` means. 

* Does it update your dependencies?

**Comment by kaygisiz** [comment]
Document updated with a usage gif: 37350dc20f1addfba051c837fb1944736f3a611c and updated description to more clear: b58031e0a406d8135946960d47f0afe265d9b781.

It doesn't update the dependencies. Features are search and find maven library, add it into gradle/dependencies and sync gradle. But it can be a great feature, you can open a new issue for feature request.

**Comment by E3V3A** [comment]
Oh! I was under the impression it was a CLI utility which showed which libraries was outdated...
